os: linux
dist: focal
language: java
jdk: openjdk11
cache:
  apt: true
  pip: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.p2"
  - $HOME/.cache/pip
services:
- xvfb
install:
  - pip3 install -r edu.cuny.hunter.hybridize.tests/requirements.txt
before_script:
  - pyenv install -v 3.10.0
  - pyenv global 3.10.0
script:
- mkdir "$HOME/git"
- pushd .
- cd "$HOME/git"
- pwd
- git clone --depth=50 --branch=pydev_9_3 https://github.com/ponder-lab/Pydev.git # Clone our fork of PyDev.
- popd
- mvn clean verify -Pjacoco coveralls:report
notifications:
  slack:
    secure: MVF8H5hIhaBw4NiT16g8KmFJMGKb64H410Sdc/UDaRXnZBHxUV8Qg4Lf70V5usWRsttqJPWCM/XzDf3vjDhx9gKq9zj+D+KchUzEu3W0UTan80JxJ8HrzDbgl5/30KXstmeTQseB1nkkwInsP49AJQh4w0fsoTjkYXNfp07TUPYqs7WM9ygyz9g7AR4kSpqjQh9b1ZAOVMKdP6we86OrWU/R6Je//4TIXiG3la60XCqB0Ad283yB7K+0wuPKVlp0SMo0sq1Wq+Pfm64wJHDPSTzVFomN7nNRFngts5GlCzEqPkEzSnQUgSYTzx+oQpPJLln48UrM9876DEKCJYV8xA01jxb0mdBwW5MWclsb+NgM8Z4rX3+kUdUixxfYEFBcPHFcFNGPLIoaq6hjFqMKOrv1xUu0SEi2wzkb245Uvd6o4ZCYOWavKo8f9m2abxID+A6pOtvx7N+VYiYgs91+OV/2goQYP9D3lng6ZzKvqGoP3SoejyV2EJb/GSYXLc7YAQ4SJWhY8NZUCpD3B72zx6Y4gPixy7/KZ6i2pvJHDEVSeA04nvPs4vPXgWnXdY7wbjJu4pRg8l4jYhJtyIzUlnu8ShGU1j7EZhNj3H1LxnFgvjRBtU2GYNuzukse5oKrh53J8d7dQZXJnB8+wcnyiN/VPym9Mc47uBGz5SPqkMM=
