os: linux
dist: focal
language: java
jdk: openjdk17
python: 3.10
cache:
  apt: true
  pip: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.p2"
  - "$HOME/.cache/pip"
before_install:
  - git show HEAD --check # Fail on whitespace errors.
  - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
  - pip install -r requirements.txt
  - mvn -s .travis.settings.xml -Dgithub.username=$GITHUB_USERNAME -Dgithub.password=$GITHUB_TOKEN spotless:check -B
addons:
  apt:
    sources:
      - sourceline: "ppa:deadsnakes/ppa"
    packages:
      - python3.10
      - python3.10-distutils
services:
- xvfb
install:
  - pip3 install -r edu.cuny.hunter.hybridize.tests/requirements.txt
  - mvn -U -s .travis.settings.xml -Dgithub.username=$GITHUB_USERNAME -Dgithub.password=$GITHUB_TOKEN -Dlogging.config.file=\${maven.multiModuleProjectDirectory}/logging.ci.properties -DtrimStackTrace=true -Dtycho.showEclipseLog=false install -B -q -DskipTests=true
before_script:
  - python3 --version
  - python3.10 --version
  - mkdir "$HOME/git"
  - pushd .
  - cd "$HOME/git"
  - pwd
  - git clone --depth=50 --branch=pydev_9_3 https://github.com/ponder-lab/Pydev.git # Clone our fork of PyDev.
  - popd
script:
- mvn -U -s .travis.settings.xml -Dgithub.username=$GITHUB_USERNAME -Dgithub.password=$GITHUB_TOKEN -Dlogging.config.file=\${maven.multiModuleProjectDirectory}/logging.ci.properties -DtrimStackTrace=true -Dtycho.showEclipseLog=false verify -Pjacoco coveralls:report -B
notifications:
  slack:
    secure: MVF8H5hIhaBw4NiT16g8KmFJMGKb64H410Sdc/UDaRXnZBHxUV8Qg4Lf70V5usWRsttqJPWCM/XzDf3vjDhx9gKq9zj+D+KchUzEu3W0UTan80JxJ8HrzDbgl5/30KXstmeTQseB1nkkwInsP49AJQh4w0fsoTjkYXNfp07TUPYqs7WM9ygyz9g7AR4kSpqjQh9b1ZAOVMKdP6we86OrWU/R6Je//4TIXiG3la60XCqB0Ad283yB7K+0wuPKVlp0SMo0sq1Wq+Pfm64wJHDPSTzVFomN7nNRFngts5GlCzEqPkEzSnQUgSYTzx+oQpPJLln48UrM9876DEKCJYV8xA01jxb0mdBwW5MWclsb+NgM8Z4rX3+kUdUixxfYEFBcPHFcFNGPLIoaq6hjFqMKOrv1xUu0SEi2wzkb245Uvd6o4ZCYOWavKo8f9m2abxID+A6pOtvx7N+VYiYgs91+OV/2goQYP9D3lng6ZzKvqGoP3SoejyV2EJb/GSYXLc7YAQ4SJWhY8NZUCpD3B72zx6Y4gPixy7/KZ6i2pvJHDEVSeA04nvPs4vPXgWnXdY7wbjJu4pRg8l4jYhJtyIzUlnu8ShGU1j7EZhNj3H1LxnFgvjRBtU2GYNuzukse5oKrh53J8d7dQZXJnB8+wcnyiN/VPym9Mc47uBGz5SPqkMM=
