os:
  - linux
  - osx
dist: focal
language: java
jdk: openjdk11
cache:
  apt: true
  pip: true
  directories:
  - "$HOME/.m2"
  - "$HOME/.p2"
  - $HOME/.cache/pip
before_install:
  - git show HEAD --check # Fail on whitespace errors.
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt install -y python3.10
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
  - sudo update-alternatives --auto python3
  - sudo apt install -y python3.10-distutils
  - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
  - export PATH=`echo $PATH | tr ":" "\n" | grep -v "/opt/pyenv/shims" | tr "\n" ":"` # Removing pyenv path from PATH which was being used by command python3.
  - export PATH=`echo $PATH | tr ":" "\n" | grep -v "/home/travis/.phpenv/shims" | tr "\n" ":"` # Removing the remaining pyenv path from PATH to make sure we are not using pyenv.
  - PATH="$PATH:/usr/bin/python3.10" # Adding our Python version to PATH.
services:
- xvfb
install:
  - pip3 install -r edu.cuny.hunter.hybridize.tests/requirements.txt
before_script:
  - python3 --version
  - python3.10 --version
script:
- mkdir "$HOME/git"
- pushd .
- cd "$HOME/git"
- pwd
- git clone --depth=50 --branch=pydev_9_3 https://github.com/ponder-lab/Pydev.git # Clone our fork of PyDev.
- popd
- mvn -U -s .travis.settings.xml -Dgithub.username=$GITHUB_USERNAME -Dgithub.password=$GITHUB_TOKEN clean verify -Pjacoco coveralls:report
notifications:
  slack:
    secure: MVF8H5hIhaBw4NiT16g8KmFJMGKb64H410Sdc/UDaRXnZBHxUV8Qg4Lf70V5usWRsttqJPWCM/XzDf3vjDhx9gKq9zj+D+KchUzEu3W0UTan80JxJ8HrzDbgl5/30KXstmeTQseB1nkkwInsP49AJQh4w0fsoTjkYXNfp07TUPYqs7WM9ygyz9g7AR4kSpqjQh9b1ZAOVMKdP6we86OrWU/R6Je//4TIXiG3la60XCqB0Ad283yB7K+0wuPKVlp0SMo0sq1Wq+Pfm64wJHDPSTzVFomN7nNRFngts5GlCzEqPkEzSnQUgSYTzx+oQpPJLln48UrM9876DEKCJYV8xA01jxb0mdBwW5MWclsb+NgM8Z4rX3+kUdUixxfYEFBcPHFcFNGPLIoaq6hjFqMKOrv1xUu0SEi2wzkb245Uvd6o4ZCYOWavKo8f9m2abxID+A6pOtvx7N+VYiYgs91+OV/2goQYP9D3lng6ZzKvqGoP3SoejyV2EJb/GSYXLc7YAQ4SJWhY8NZUCpD3B72zx6Y4gPixy7/KZ6i2pvJHDEVSeA04nvPs4vPXgWnXdY7wbjJu4pRg8l4jYhJtyIzUlnu8ShGU1j7EZhNj3H1LxnFgvjRBtU2GYNuzukse5oKrh53J8d7dQZXJnB8+wcnyiN/VPym9Mc47uBGz5SPqkMM=
