source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               plugin.xml,\
               flask.xml,\
               pandas.xml,\
               functools.xml,\
               tensorflow.xml,\
               numpy.xml,\
               numpy_turtle.xml,\
               pytest.xml,\
               click.xml,\
               abseil.xml,\
               turtles.xml
jre.compilation.profile = JavaSE-25
